// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
 const sidebars = {
  // Automatically generate sidebars for categorized topics
  cProgrammingFundamentalsSidebar: [{ type: 'autogenerated', dirName: '01_c_fundamentals' }],
  coreLanguageFeaturesSidebar: [{ type: 'autogenerated', dirName: '02_core_language_features' }],
  memoryManagementSidebar: [{ type: 'autogenerated', dirName: '03_memory_management_and_pointers' }],
  advancedLanguageConceptsSidebar: [{ type: 'autogenerated', dirName: '04_advanced_language_concepts' }],
  debuggingErrorHandlingSidebar: [{ type: 'autogenerated', dirName: '05_debugging_and_error_handling' }],
  fileIOHandlingSidebar: [{ type: 'autogenerated', dirName: '06_file_io_handling' }],
  librariesProgramOrganizationSidebar: [{ type: 'autogenerated', dirName: '07_libraries_and_program_organization' }],
  dataStructuresSidebar: [{ type: 'autogenerated', dirName: '08_data_structures' }],
  systemProgrammingSidebar: [{ type: 'autogenerated', dirName: '09_system_programming_concepts' }],
};


export default sidebars;
